### ISSUE TITLE
ModuleNotFoundError: No module named 'glyce.data'

### ISSUE THREAD

**Issue by RingoTC** [ShannonAI/glyce#10]
When I run bash scripts/chnsenticorp_bert.sh.
I get the following error message.

```
Traceback (most recent call last):
  File "/data/lh/glyce/glyce/bin/run_bert_classifier.py", line 28, in <module>
    from glyce.dataset_readers.bert_sent_pair import *
  File "/data/lh/glyce/glyce/dataset_readers/bert_sent_pair.py", line 35, in <module>
    from glyce.data.data_utils import *
ModuleNotFoundError: No module named 'glyce.data'
```

How can I solve it?

**Comment by ghost** [comment]
Please pull the latest code. We already fix this. Sorry for my careless. Many thanks. :-)
