### ISSUE TITLE
a question about config

### ISSUE THREAD

**Issue by tyistyler** [ShannonAI/glyce#25]
Excuse me, I don't find the config files in the path?is ia any question ?
______________________________________
Traceback (most recent call last):
  File "./bin/run_bert_glyce_tagger.py", line 404, in <module>
    main()
  File "./bin/run_bert_glyce_tagger.py", line 394, in main
    config = merge_config(args_config)
  File "./bin/run_bert_glyce_tagger.py", line 385, in merge_config
    model_config = Config.from_json_file(model_config_path)
  File "/content/drive/My Drive/NER/glyce/glyce/dataset_readers/bert_config.py", line 44, in from_json_file
    with open(json_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lixiaoya/dataset/'

**Comment by ghost** [comment]
Please change the python path. 
Many thanks!

**Comment by Crescentz** [comment]
@stepperL  Pls ?
```
Traceback (most recent call last):
  File "/home/zy/CODE/bishe/test/test.py", line 18, in <module>
    glyce_embedding = CharGlyceEmbedding(glyce_config)
  File "/home/zy/CODE/bishe/glyce/glyce/layers/char_glyph_embedding.py", line 65, in __init__
    self.char_embedding = nn.Embedding(len(self.config.idx2char), self.config.char_embsize) # (4452, 13, 13)
TypeError: object of type 'NoneType' has no len()
```

What this problem?
