### ISSUE TITLE
bq_glyce_bert

### ISSUE THREAD

**Issue by zhaiqi** [ShannonAI/glyce#27]
您好，我想问一下，为什么在这个数据集上训练的结果的ACC和F1值始终在一样的呢？

**Comment by Crescentz** [comment]
> 您好，我想问一下，为什么在这个数据集上训练的结果的ACC和F1值始终在一样的呢？
```

Traceback (most recent call last):
  File "/home/zy/CODE/bishe/test/test.py", line 18, in <module>
    glyce_embedding = CharGlyceEmbedding(glyce_config)
  File "/home//glyce/glyce/layers/char_glyph_embedding.py", line 65, in __init__
    self.char_embedding = nn.Embedding(len(self.config.idx2char), self.config.char_embsize) # (4452, 13, 13)
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1
```
你好，哥们，你遇到这事了吗，扎解决的
