### ISSUE TITLE
bq 数据集没有找到

### ISSUE THREAD

**Issue by Li-rr** [ShannonAI/glyce#31]
您好，我下载了bq数据集，设置了数据集路径，为什么会报这样的错，是需要数据预处理吗

```python
input_file /home/lrr/workspace/glyce_datset/sent_pair/bq/train.json
Traceback (most recent call last):
  File "/home/lrr/workspace/glyce/glyce/bin/run_bert_glyce_classifier.py", line 388, in <module>
    main()
  File "/home/lrr/workspace/glyce/glyce/bin/run_bert_glyce_classifier.py", line 380, in main
    train_loader, dev_loader, test_loader, num_train_steps, label_list = load_data(config)
  File "/home/lrr/workspace/glyce/glyce/bin/run_bert_glyce_classifier.py", line 133, in load_data
    train_examples = data_processor.get_train_examples(config.data_dir)
  File "/home/lrr/workspace/glyce/glyce/dataset_readers/bert_sent_pair.py", line 132, in get_train_examples
    self._read_tsv(os.path.join(data_dir, "train.json")), "train")
  File "/home/lrr/workspace/glyce/glyce/dataset_readers/bert_data_utils.py", line 78, in _read_tsv
    with open(input_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lrr/workspace/glyce_datset/sent_pair/bq/train.json'
```

这是我的数据集设置：
```shell
echo "data_sign: $data_sign"
#data_dir=/data/nfsdata/nlp/datasets/sentence_pair/bq_corpus
data_dir=/home/lrr/workspace/glyce_datset/sent_pair/bq
output_dir=../export-model # change save_path !!!
```

这是文件夹内容

![image](https://user-images.githubusercontent.com/23090313/97066668-c153f400-15e9-11eb-91ed-a2a9d26411fd.png)

**Comment by okcd00** [comment]
我也遇到了一样的问题，改一下数据加载的函数可能就可以了。( Issue #38 )

**Comment by Li-rr** [comment]
> 我也遇到了一样的问题，改一下数据加载的函数可能就可以了。( Issue #38 )

谢谢您，我去试试
